name: minent
channels:
  - pytorch
  - conda-forge
dependencies:
  - pip=24.0
  - tqdm=4.66.2
  - torchvision=0.17.1
  - torchaudio=2.2.1
  - pygame=2.5.2
  - wandb=0.16.3
  - cudnn=8.9.7.29
  - ray-rllib=1.11.1
  - pytest=8.1.1
  - sacred=0.8.5
  - ipython=8.18.1
  - sqlite=3.45.2
  - pip:
    - -e boltzmann-policy-distribution
    - -e overcooked_ai
