name: minent
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - ray-rllib=1.11
  - numpy=1.22.2
  - scipy=1.6.3
  - cudatoolkit
  - cudnn
  - cuda-nvcc
  - pytorch=2.0
  - pip=24.0
  - pygame=2.5.2
  - pytest=8.1.1
  - wandb=0.16.3
  - sqlite=3.45.2
  - sacred=0.8.5
  - tqdm=4.66.2
  - pip:
    - -e boltzmann-policy-distribution
    - -e overcooked_ai

